### PR TITLE
Prevent ARRAYSIZE undef

### PR DESCRIPTION
**Pull request by GAMMACASE**
Currently this undef prevents compilation of the mm plugins with latest sdk2013 variants and source2 hl2sdk's (cs2, dota, deadlock) if certain include order is met. The cause is metamod_oslink.h which undefs the definition from hl2sdk coming from commonmacros.h which later results in compilation errors if ARRAYSIZE is used anywhere down the line.
https://github.com/alliedmodders/hl2sdk/blob/4c27c1305c5e042ae1f62f6dc6ba7e96fd06e05d/public/tier0/commonmacros.h#L152-L155

If there's someone with more in-depth knowledge on the history of this undef or if it's still needed, I'd gladly discuss other solutions to this issue, but currently all the hl2sdks do build fine with that removed on the modern msvc, where I assume problems might arise if older build tooling is used? I do see that the sdk definitions of ARRAYSIZE are just a copy from win api winnt.h header, but that doesn't get used anyhow in the build process so shouldn't result in a conflict anyhow other than if older msvc forcefully dragged that include in?

Additionally this pr fixes gcc compilation of the latest sdk2013 hl2sdk variants by adding ``-Wno-class-memaccess`` compilation flag as otherwise it fails to compile with that error (tested on gcc 9.4).

### CODE REVIEW

**Comment by tschumann** [comment]
Not sure about its history in Metamod: Source but in other similar projects it looks like it's been fiddled with over the years to get things compiling on Windows: https://github.com/ValveSoftware/halflife/blob/master/engine/eiface.h#L422, https://github.com/ValveSoftware/halflife/blob/master/common/winsani_in.h, https://github.com/ValveSoftware/halflife/blob/master/common/winsani_out.h and https://github.com/Bots-United/metamod-p/blob/af1c4b67dd1837d622181c68168641cf01108c34/hlsdk/engine/eiface.h#L449

**Review by psychonic — APPROVED** [review]
